name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

env:
  clippy_rust_version: '1.84'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.clippy_rust_version }}
          components: clippy
      - run: cargo clippy --workspace --all-targets -- -D warnings

  toml_validation:
    runs-on: ubuntu-latest
    container:
      image: tamasfe/taplo:0.9.3
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: taplo lint
        run: taplo lint
      - name: taplo fmt
        run: taplo fmt --check --diff
